apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "accounts-service.fullname" . }}
  labels:
    {{- include "accounts-service.labels" . | nindent 4 }}
data:
  BOOTSTRAP_SERVERS_KAFKA: "http://{{.Release.Name}}-kafka-broker-0.{{.Release.Name}}-kafka-broker-headless.{{.Release.Namespace}}.svc.cluster.local:9092"
  application.yml: |
    gatewayHost: gateway-service.{{.Release.Namespace}}.svc.cluster.local
    ribbon:
      enabled: false
    spring:
      kafka:
        template:
          observation-enabled: true
        bootstrap-servers: "http://{{.Release.Name}}-kafka-broker-0.{{.Release.Name}}-kafka-broker-headless.{{.Release.Namespace}}.svc.cluster.local:9092"
        producer:
          bootstrap-servers: "http://{{.Release.Name}}-kafka-broker-0.{{.Release.Name}}-kafka-broker-headless.{{.Release.Namespace}}.svc.cluster.local:9092"
          properties:
            spring:
              json:
                add:
                  type:
                    headers: false
            acks: all
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        admin:
          client-id: myapp
        properties:
          security.protocol: PLAINTEXT
      autoconfigure:
        exclude:
          - org.springframework.cloud.stream.config.BinderAutoConfiguration
          - org.springframework.cloud.stream.messaging.SourceBindingServiceConfiguration
      stream:
        bindings:
          input:
            destination: unused
            binder: none
          output:
            destination: unused
            binder: none
        rabbit:
          enabled: false
      cloud:
        loadbalancer:
          enabled: false
          ribbon:
            enabled: false
        stream:
          rabbit:
            enabled: false
        config:
          enabled: false
      application:
        name: accountsService
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri:  http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/master
      datasource:
        url: {{ tpl .Values.config.database_url . | quote }}
        username: {{ .Values.config.database_username | quote }}
        password: mysecret
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform:
          org.hibernate.dialect.PostgreSQLDialect
      liquibase:
        url: {{ tpl .Values.config.database_url . | quote }}
        change-log: classpath:liquibase/db.changelog-master.xml
        parameters:
          app.schema-name: accounts
          file-opener-class: org.springframework.boot.loader.jar.JarFileOpener
        clear-checksums: false
        enabled: true
        user: {{ .Values.config.database_username | quote }}
        password: mysecret
    management:
      zipkin:
        tracing:
          endpoint:  "http://{{ .Release.Name }}-zipkin:9411/api/v2/spans" # Эндпойнт Zipkin для приема спанов
      tracing:
        sampling:
          probability: 1 # Сэмплируем все запросы
      endpoints:
        web:
          exposure:
            include: refresh,busrefresh,busshutdown,health,info,metrics,prometheus,prometheus
      endpoint:
        health:
          show-details: always
    eureka:
      instance:
        hostname: localhost
        prefer-ip-address: true
      client:
        enabled: false
        serviceUrl:
          defaultZone: http://eureka-service-discovery:8761/eureka/
    server:
      port: 8084
    logging:
      level:
        org:
          springframework:
            web:
              filter:
                CommonsRequestLoggingFilter: DEBUG