apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: accounts-service
  name: accounts-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: accounts-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: accounts-service
    spec:
      containers:
        - env:
            - name: NOTIFICATIONS_SERVICE_PORT
              value: "8081"
            - name: SPRING_CONFIG_LOCATION
              value: file:///app/config/application.yml
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
          image: "accounts-service:0.0.1-SNAPSHOT"
          name: accounts-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8084
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "accounts-service.fullname" . }}
      restartPolicy: Always
