apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    app: accounts-service
    io.kompose.service: accounts-service
  name: accounts-service
spec:
  type: {{.Values.service.type }}
  ports:
    - name: "http"
      port: 80 #8084
      targetPort: 8084 #8084
      protocol: TCP
  selector:
    app: accounts-service
