cluster.name: docker-cluster
network.host: 0.0.0.0
discovery.type: single-node
http.port: 9200
transport.port: 9300

xpack.security.transport.ssl.enabled: false
xpack.security.http.ssl.enabled: false
xpack.security.authc.token.enabled: false
xpack.security.enabled: false
#xpack.security.transport.enabled: false