spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloakContainer:7980/realms/master
  datasource:
    url: jdbc:postgresql://localhost:5433/notifications
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    url: jdbc:postgresql://localhost:5433/notifications
    change-log: classpath:liquibase/db.changelog-master.xml
    parameters:
      app.schema-name: accounts
      file-opener-class: org.springframework.boot.loader.jar.JarFileOpener
    clear-checksums: false
    enabled: true
    user: myuser
    password: secret
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,busshutdown,health,info
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service-discovery:8761/eureka/
server:
  port: 8084
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG