text-to-print: "Текст до изменений" # Property в микросервисе, которое мы будем изменять прямо на лету
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_KAFKA:localhost:9092}
    consumer:
      group-id: currency-rates-grp
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        acks: all
        spring.json.value.default.type: ru.muravin.bankapplication.currencyExchangeService.dto.CurrencyRateDto
        spring.json.trusted.packages: ru.muravin.bankapplication
    listener:
      ack-mode: MANUAL_IMMEDIATE
  datasource:
    url: jdbc:postgresql://localhost:5433/notifications
    username: myuser
    password: secret
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    url: jdbc:postgresql://localhost:5433/notifications
    change-log: classpath:liquibase/db.changelog-master.xml
    parameters:
      app.schema-name: currencyExchange
      file-opener-class: org.springframework.boot.loader.jar.JarFileOpener
    clear-checksums: false
    enabled: true
    user: myuser
    password: secret
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,busshutdown,health,info
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service-discovery:8761/eureka/
server:
  port: 8093