spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  kafka:
    producer:
      bootstrap-servers: ${BOOTSTRAP_SERVERS_KAFKA:localhost:9092}
      properties:
        acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      client-id: myapp
    properties:
      security.protocol: PLAINTEXT
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,busshutdown,health,info
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    enabled:  false
    serviceUrl:
      defaultZone: http://eureka-service-discovery:8761/eureka/