cashInCashOutService:
  fullUrl: http://172.21.48.1:8095
  client: cashInCashOutService
  secret: F3PnrhRuMtxh30N67vgxAkOJqY3KYpwW
  scope: profile
  registrationId: cashInCashOutService
  tokenUri: http://keycloak:8080/realms/master/protocol/openid-connect/token
spring:
  cloud:
    gateway:
      routes:
        - id: all
          uri: http:/**    # адрес сервиса B
          predicates:
            - Path=/**
          filters:
            - TokenRelay=gateway-client      # используем TokenRelay с нашим clientRegistrationId
  security:

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans # Эндпойнт Zipkin для приема спанов
  tracing:
    sampling:
      probability: 1 # Сэмплируем все запросы
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,busshutdown,health,info
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service-discovery:8761/eureka/