text-to-print: "Текст до изменений" # Property в микросервисе, которое мы будем изменять прямо на лету
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS_KAFKA:localhost:9092}
    consumer:
      group-id: notifications-grp
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: java.util.LinkedHashMap
            trusted:
              packages: ru.muravin.*
        acks: 1
    listener:
      observation-enabled: true
      ack-mode: MANUAL_IMMEDIATE
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/master
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,busshutdown,health,info
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service-discovery:8761/eureka/