apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cash-in-cash-out-service
  name: cash-in-cash-out-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cash-in-cash-out-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: cash-in-cash-out-service
    spec:
      containers:
        - env:
            - name: NOTIFICATIONS_SERVICE_PORT
              value: "8081"
          envFrom:
            - configMapRef:
                name: env
          image: cash-in-cash-out-service
          name: cash-in-cash-out-service
          ports:
            - containerPort: 8095
              protocol: TCP
      restartPolicy: Always
