apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cash-in-cash-out-service
    app: cash-in-cash-out-service
  name: cash-in-cash-out-service
spec:
  type: {{.Values.service.type }}
  ports:
    - name: "http"
      port: 80 #8095
      targetPort: 8095 #8095
      protocol: TCP
  selector:
    app: cash-in-cash-out-service
