apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cash-in-cash-out-service
  name: cash_in_cash_out-service
spec:
  ports:
    - name: "8095"
      port: 8095
      targetPort: 8095
  selector:
    io.kompose.service: cash-in-cash-out-service
