{{- if .Values.gatewayIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $value := .Values.gatewayIngress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.gatewayIngress.className }}
  rules:
    - http:
        paths:
          {{- range .Values.gatewayIngress.services }}
          - path: {{ .path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .backend.service }}
                port:
                  number: {{ .backend.port }}
          {{- end }}
{{- end }}