apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  realm-config.json: |
      {
        "realm": "master",
        "enabled": true,
        "attributes": {
          "frontendUrl": "http://{{.Release.Name}}-keycloak.{{.Release.Namespace}}.svc.cluster.local:8080"
        },
        "clients": [
          {
            "clientId": "cashInCashOutService",
            "secret": "F3PnrhRuMtxh30N67vgxAkOJqY3KYpwW",
            "redirectUris": ["*"],
            "webOrigins": [],
            "directAccessGrantsEnabled": true,
            "standardFlowEnabled": true,
            "implicitFlowEnabled": true,
            "serviceAccountsEnabled": true,
            "publicClient": false,
            "authorizationServicesEnabled": true,
            "defaultClientScopes": ["openid", "profile"],
            "optionalClientScopes": []
          }
        ]
      }