rootProject.name = "bankMicroservicesApplication"
include("accounts_service")
include("antifraud_service")
include("cash_in_cash_out_service")
include("config_server")
include("currency_exchange_service")
include("eureka_service_discovery")
include("exchange_generator_service")
include("notifications_service")
include("transfer_service")
include("ui_service")
include("gateway")