apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: gateway-service
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gateway-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: gateway-service
    spec:
      containers:
        - env:
            - name: SPRING_CONFIG_LOCATION
              value: file:///app/config
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
          image: "gateway-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          name: gateway-service
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "gateway-service.fullname" . }}
