apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-service-monitor
  namespace: default
  labels:
    release: myapp

spec:
  jobLabel: gateway-service
  endpoints:
    - port: "http"                 # порт из Service
      path: /actuator/prometheus       # путь до метрик
      interval: 15s                  # интервал сбора
      #scrapeTimeout: 10s            # таймаут
  selector:
    matchLabels:
      app: gateway-service
  namespaceSelector:
    any: true