apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: gateway-service
    app: gateway-service
  name: gateway-service
spec:
  type: {{.Values.service.type }}
  ports:
    - name: "http"
      port: 80 # 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: gateway-service
