scrape_configs:
  - job_name: 'ui-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'ui-service:8087' ]
        labels:
          application: 'ui-service'