scrape_configs:
  - job_name: 'ui-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'ui-service:8087' ]
        labels:
          application: 'ui-service'
  - job_name: 'notifications-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'notifications-service:8081' ]
        labels:
          application: 'notifications-service'
  - job_name: 'accounts-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'service:8084' ]
        labels:
          application: 'service'

  - job_name: 'transfer-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'transfer-service:8100' ]
        labels:
          application: 'transfer-service'
  - job_name: 'cash_in_cash_out-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'cash_in_cash_out-service:8092' ]
        labels:
          application: 'cash_in_cash_out-service'
  - job_name: 'exchange-generation-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'exchange-generation-service:8095' ]
        labels:
          application: 'exchange-generation-service'
  - job_name: 'exchange-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'exchange-service:8093' ]
        labels:
          application: 'exchange-service'

  - job_name: 'gateway-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'gateway-service:8080' ]
        labels:
          application: 'gateway-service'
  - job_name: 'antifraud-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'antifraud-service:8096' ]
        labels:
          application: 'antifraud-service'