spring:
  application:
    name: gateway
  config:
    import: configserver:http://127.0.0.1:8888
server:
  port: 8080


management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always