apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
data:
  application.yml: |
    gatewayHost: gateway-service.{{.Release.Namespace}}.svc.cluster.local
    server:
      port: 8100
    ribbon:
      enabled: false
    spring:
      cloud:
        loadbalancer:
          enabled: false
          ribbon:
            enabled: false
        config:
          enabled: false
      application:
        name: transferService
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri:  http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/master
    management:
      endpoints:
        web:
          exposure:
            include: refresh,busrefresh,busshutdown,health,info
      endpoint:
        health:
          show-details: always
    eureka:
      instance:
        hostname: localhost
        prefer-ip-address: true
      client:
        enabled: false
        serviceUrl:
          defaultZone: http://eureka-service-discovery:8761/eureka/   # URL Eureka сервера

    logging:
      level:
        org:
          springframework:
            web:
              filter:
                CommonsRequestLoggingFilter: DEBUG
