apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
data:
  application.yml: |
    gatewayHost: gateway-service.{{.Release.Namespace}}.svc.cluster.local
    server:
      port: 8100
    ribbon:
      enabled: false
    spring:
      kafka:
        template:
          observation-enabled: true
        bootstrap-servers: "http://{{.Release.Name}}-kafka-broker-0.{{.Release.Name}}-kafka-broker-headless.{{.Release.Namespace}}.svc.cluster.local:9092"
        producer:
          bootstrap-servers: "http://{{.Release.Name}}-kafka-broker-0.{{.Release.Name}}-kafka-broker-headless.{{.Release.Namespace}}.svc.cluster.local:9092"
          properties:
            spring:
              json:
                add:
                  type:
                    headers: false
            acks: all
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        admin:
          client-id: myapp
        properties:
          security.protocol: PLAINTEXT
      cloud:
        loadbalancer:
          enabled: false
          ribbon:
            enabled: false
        config:
          enabled: false
      application:
        name: transferService
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri:  http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/master
    management:
      zipkin:
        tracing:
          endpoint: http://ПоправитьНаКорректныйАдрес/api/v2/spans # Эндпойнт Zipkin для приема спанов
      tracing:
        sampling:
          probability: 1 # Сэмплируем все запросы
      endpoints:
        web:
          exposure:
            include: refresh,busrefresh,busshutdown,health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
    eureka:
      instance:
        hostname: localhost
        prefer-ip-address: true
      client:
        enabled: false
        serviceUrl:
          defaultZone: http://eureka-service-discovery:8761/eureka/   # URL Eureka сервера

    logging:
      level:
        org:
          springframework:
            web:
              filter:
                CommonsRequestLoggingFilter: DEBUG
