apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: transfer-service
  name: transfer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transfer-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: transfer-service
    spec:
      initContainers:
        - name: delay
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Delay 70 sec"
              sleep 70
              echo "Delay finished, starting deployment"
      containers:
        - env:
            - name: NOTIFICATIONS_SERVICE_PORT
              value: "8081"
            - name: SPRING_CONFIG_LOCATION
              value: file:///app/config/application.yml
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "512Mi"
          image: "transfer-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          name: transfer-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8100
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          ports:
            - containerPort: 8100
              protocol: TCP
      restartPolicy: Always
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "transfer-service.fullname" . }}
