apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: transfer-service
    app: transfer-service
  name: transfer-service
spec:
  type: {{.Values.service.type }}
  ports:
    - name: "http"
      port: 80 #8100
      targetPort: 8100
      protocol: TCP
  selector:
    app: transfer-service
