apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: transfer-service
  name: transfer-service
spec:
  ports:
    - name: "8100"
      port: 80
      targetPort: 8100
  selector:
    io.kompose.service: transfer-service
