apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "antifraud-service.fullname" . }}
  labels:
    {{- include "antifraud-service.labels" . | nindent 4 }}
data:
  application.yml: |
    spring:
      cloud:
        config:
          enabled: false
      application:
        name: antifraudService
      server:
        port: 8096
      rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://keycloak:8080/realms/master
    management:
      endpoints:
        web:
          exposure:
            include: refresh,busrefresh,busshutdown,health,info
      endpoint:
        health:
          show-details: always
    eureka:
      instance:
        hostname: localhost
        prefer-ip-address: true
      client:
        enabled: false
        serviceUrl:
          defaultZone: http://eureka-service-discovery:8761/eureka/

    logging:
      level:
        org:
          springframework:
            web:
              filter:
                CommonsRequestLoggingFilter: DEBUG