apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: antifraud-service
    app: antifraud-service
  name: antifraud-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: antifraud-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: antifraud-service
        app: antifraud-service
    spec:
      initContainers:
        - name: delay
          image: curlimages/curl:latest
          command:
            - sh
            - -c
            - |
              echo "Delay 70 sec"
              sleep 70
              echo "Delay finished, starting deployment"
      containers:
        - env:
            - name: BOOTSTRAP_SERVERS_KAFKA
              value: "http://{{.Release.Name}}-kafka-broker-0.{{.Release.Name}}-kafka-broker-headless.{{.Release.Namespace}}.svc.cluster.local:9092"
            - name: NOTIFICATIONS_SERVICE_PORT
              value: "8081"
            - name: SPRING_CONFIG_LOCATION
              value: file:///app/config/application.yml
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
          imagePullPolicy: IfNotPresent
          image: "antifraud-service:0.0.1-SNAPSHOT"
          name: antifraud-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8096
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "512Mi"
          ports:
            - containerPort: 8096
              protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "antifraud-service.fullname" . }}
      restartPolicy: Always
