apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: antifraud-service
    app: antifraud-service
  name: antifraud-service
spec:
  type: {{.Values.service.type }}
  ports:
    - name: "http"
      port: 80 #8096
      targetPort: 8096 #8096
      protocol: TCP

  selector:
    app: antifraud-service
