apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notifications-service.fullname" . }}
  labels:
    {{- include "notifications-service.labels" . | nindent 4 }}
data:
  application.yml: |
    text-to-print: "Текст до изменений" # Property в микросервисе, которое мы будем изменять прямо на лету
    spring:
      rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://keycloak:8080/realms/master
    eureka:
      instance:
        hostname: localhost
        prefer-ip-address: true
      client:
        serviceUrl:
          defaultZone: http://eureka-service-discovery:8761/eureka/
      application:
        name: notificationsService
      config:
        import: configserver:http://config-server:8888
      datasource:
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
        password: ${SPRING_DATASOURCE_PASSWORD}
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform:
          org.hibernate.dialect.PostgreSQLDialect
      liquibase:
        url: ${SPRING_DATASOURCE_URL}
        change-log: classpath:liquibase/db.changelog-master.xml
        parameters:
          app.schema-name: notifications
          file-opener-class: org.springframework.boot.loader.jar.JarFileOpener
        clear-checksums: false
        enabled: true
        user: myuser
        password: secret
    server:
      port: 8081

    management:
      endpoints:
        web:
          exposure:
            include: refresh,busrefresh,busshutdown,health,info
      endpoint:
        health:
          show-details: always
