apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: notifications-service
  name: notifications-service
spec:
  ports:
    - name: "8081"
      port: 80
      targetPort: 8081
  selector:
    io.kompose.service: notifications-service
