spring:
  application:
    name: currencyExchangeService
  config:
    import: configserver:http://127.0.0.1:8888
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform:
      org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    url: ${SPRING_DATASOURCE_URL}
    change-log: classpath:liquibase/db.changelog-master.xml
    parameters:
      app.schema-name: currencyExchange
      file-opener-class: org.springframework.boot.loader.jar.JarFileOpener
    clear-checksums: false
    enabled: true
    user: myuser
    password: secret
server:
  port: ${SERVER_PORT:8091}

