apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: config-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: config-server
    spec:
      containers:
        - env:
            - name: CONFIG_SERVER_PORT
              value: "8888"
          envFrom:
            - configMapRef:
                name: env
          image: config-server
          livenessProbe:
            exec:
              command:
                - wget
                - --spider
                - -q
                - http://localhost:8888/actuator/health
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: config-server
          ports:
            - containerPort: 8888
              protocol: TCP
      hostname: config-server
      restartPolicy: Always
