apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-service.fullname" . }}
  labels:
    {{- include "exchange-service.labels" . | nindent 4 }}
data:
  application.yml: |
    server:
      port: 8093
    text-to-print: "Текст до изменений" # Property в микросервисе, которое мы будем изменять прямо на лету
    spring:
      cloud:
        config:
          enabled: false
      application:
        name: currencyExchangeService
      rabbitmq:
        host: rabbitmq
        port: 5672
        username: guest
        password: guest
      datasource:
        url: {{ tpl .Values.config.database_url . | quote }}
        username: {{ tpl .Values.config.database_username . | quote }}
        password: mysecret
      security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri:  http://{{ .Release.Name }}-keycloak.{{ .Release.Namespace }}.svc.cluster.local:8080/realms/master
      jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        database-platform:
          org.hibernate.dialect.PostgreSQLDialect
      liquibase:
        url: {{ tpl .Values.config.database_url . | quote }}
        change-log: classpath:liquibase/db.changelog-master.xml
        parameters:
          app.schema-name: currencyExchange
          file-opener-class: org.springframework.boot.loader.jar.JarFileOpener
        clear-checksums: false
        enabled: true
        user: {{ tpl .Values.config.database_username . | quote }}
        password: mysecret
    management:
      endpoints:
        web:
          exposure:
            include: refresh,busrefresh,busshutdown,health,info
    eureka:
      instance:
        hostname: localhost
        prefer-ip-address: true
      client:
        enabled: false
        serviceUrl:
          defaultZone: http://eureka-service-discovery:8761/eureka/
