apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: exchange-service
  name: exchange-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: exchange-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: exchange-service
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "exchange-service.fullname" . }}
      containers:
        - env:
            - name: NOTIFICATIONS_SERVICE_PORT
              value: "8081"
            - name: SPRING_CONFIG_LOCATION
              value: file:///app/config/application.yml
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
          image: "currency-exchange-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "512Mi"
          name: exchange-service
          ports:
            - containerPort: 8093
              protocol: TCP
      restartPolicy: Always
