apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: exchange-service
  name: exchange-service
spec:
  ports:
    - name: "8093"
      port: 8093
      targetPort: 8093
  selector:
    io.kompose.service: exchange-service
