{
 "title": "Бизнес логика банковских метрик",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "login",
    "label": "Login",
    "query": "label_values(login_total, login)"
   },
   {
    "name": "recipientAccount",
    "label": "Счет получателя",
    "query": "label_values(transfer_total, recipientAccount)"
   },
   {
    "name": "senderAccount",
    "label": "Счет отправителя",
    "query": "label_values(transfer_total, senderAccount)"
   }
  ]
 },
 "panels": [
  {
   "title": "Логины пользователей",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(login_total{status=\"success\"})",
     "legendFormat": "Успешные логины"
    },
    {
     "expr": "sum(login_total{status=\"failure\"})",
     "legendFormat": "Неуспешные логины"
    }
   ]
  },
  {
   "title": "Переводы",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(transfer_total{status=\"success\"})",
     "legendFormat": "Успешные переводы"
    },
    {
     "expr": "sum(transfer_total{status=\"failure\"})",
     "legendFormat": "Неуспешные переводы"
    }
   ]
  },
  {
   "title": "Обновления курса валют",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(currency_rates_updated_total)",
     "legendFormat": "Обновления курса"
    }
   ]
  },
  {
   "title": "Заблокированные операции",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(operationBlocked_total{recipientAccount!=\"NONE\", senderAccount!=\"NONE\"}) by (login)",
     "legendFormat": "{{login}}"
    }
   ]
  },
  {
   "title": "История переводов",
   "type": "timeseries",
   "description": "Количество успешных и неуспешных переводов по времени",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "rate(transfer_total{status=\"success\"}[5m])",
     "legendFormat": "Успешные переводы"
    },
    {
     "expr": "rate(transfer_total{status=\"failure\"}[5m])",
     "legendFormat": "Неуспешные переводы"
    }
   ]
  },
  {
   "title": "Ошибка отправки уведомлений",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(failedToSendNotification_total)",
     "legendFormat": "Неудачные уведомления"
    }
   ]
  },
  {
   "title": "Неудачные уведомления",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(failedToSendNotification_total)",
     "legendFormat": "Неудачные уведомления"
    }
   ]
  },
  {
   "title": "Заблокированные операции по пользователям",
   "type": "timeseries",
   "description": "Просмотр количества заблокированных операций",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(operationBlocked_total{recipientAccount!=\"NONE\", senderAccount!=\"NONE\"}) by (login)",
     "legendFormat": "{{login}}"
    }
   ]
  }
 ]
}