apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: ui-service
  name: ui-service
spec:
  ports:
    - name: "8087"
      port: 80
      targetPort: 8087
  selector:
    io.kompose.service: ui-service
