apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-generation-service.fullname" . }}
  labels:
    {{- include "exchange-generation-service.labels" . | nindent 4 }}
data:
  application.yml: |
    gatewayHost: gateway-service.{{.Release.Namespace}}.svc.cluster.local
    server:
      port: 8092
    ribbon:
      enabled: false
    spring:
      template:
        observation-enabled: true
      kafka:
        bootstrap-servers: "http://{{.Release.Name}}-kafka-broker-0.{{.Release.Name}}-kafka-broker-headless.{{.Release.Namespace}}.svc.cluster.local:9092"
        producer:
          bootstrap-servers: "http://{{.Release.Name}}-kafka-broker-0.{{.Release.Name}}-kafka-broker-headless.{{.Release.Namespace}}.svc.cluster.local:9092"
          properties:
            acks: all
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        admin:
          client-id: myapp
        properties:
          security.protocol: PLAINTEXT
      cloud:
        loadbalancer:
          enabled: false
          ribbon:
            enabled: false
        config:
          enabled: false
      application:
        name: exchangeGeneratorService
    management:
      zipkin:
        tracing:
          endpoint: http://ПоправитьНаКорректныйАдрес:9411/api/v2/spans # Эндпойнт Zipkin для приема спанов
      tracing:
        propagation:
          type: B3
        sampling:
          probability: 1 # Сэмплируем все запросы
      endpoints:
        web:
          exposure:
            include: refresh,busrefresh,busshutdown,health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
    eureka:
      instance:
        hostname: localhost
        prefer-ip-address: true
      client:
        enabled: false
        serviceUrl:
          defaultZone: http://eureka-service-discovery:8761/eureka/
    logging:
      level:
        org.apache.kafka: DEBUG
        org.springframework.kafka: DEBUG