apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exchange-generation-service.fullname" . }}
  labels:
    {{- include "exchange-generation-service.labels" . | nindent 4 }}
data:
  application.yml: |
    gatewayHost: gateway-service.{{.Release.Namespace}}.svc.cluster.local
    server:
      port: 8092
    ribbon:
      enabled: false
    spring:
      cloud:
        loadbalancer:
          enabled: false
          ribbon:
            enabled: false
        config:
          enabled: false
      application:
        name: exchangeGeneratorService
    management:
      endpoints:
        web:
          exposure:
            include: refresh,busrefresh,busshutdown,health,info
      endpoint:
        health:
          show-details: always
    eureka:
      instance:
        hostname: localhost
        prefer-ip-address: true
      client:
        enabled: false
        serviceUrl:
          defaultZone: http://eureka-service-discovery:8761/eureka/