apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: exchange-generation-service
  name: exchange-generation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: exchange-generation-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: exchange-generation-service
    spec:
      containers:
        - env:
            - name: NOTIFICATIONS_SERVICE_PORT
              value: "8081"
            - name: SPRING_CONFIG_LOCATION
              value: file:///app/config/application.yml
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
          image: "exchange-generator-service:0.0.1-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          name: exchange-generation-service
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8092
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 3
          resources:
            limits:
              memory: "1Gi"
            requests:
              memory: "512Mi"
          ports:
            - containerPort: 8092
              protocol: TCP
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "exchange-generation-service.fullname" . }}
      restartPolicy: Always
