apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: exchange-generation-service
    app: exchange-generation-service
  name: exchange-generation-service
spec:
  type: {{.Values.service.type }}
  ports:
    - name: "http"
      port: 80 #8092
      targetPort: 8092 #8092
      protocol: TCP
  selector:
    app: exchange-generation-service
