spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding:
      true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7980/realms/master
          #jwk-set-uri: http://localhost:7980/realms/demo/protocol/openid-connect/certs
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,busshutdown,health,info
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   # URL Eureka сервера

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG