spring:
  cloud:
    gateway:
      routes:
        - id: all
          uri: http:/**    # адрес сервиса B
          predicates:
            - Path=/**
          filters:
            - TokenRelay=gateway-client      # используем TokenRelay с нашим clientRegistrationId
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: http://localhost:7980/realms/demo/protocol/openid-connect/token
        registration:
          gateway-client:
            provider: keycloak
            client-id: gateway-client        # ID зарегистрированного клиента
            client-secret: 5sHK5bQy8UTTX7ZqQGmJsQmm5yD9TeDU
            scope: resource.read
            authorization-grant-type: client_credentials
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,busshutdown,health,info
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   # URL Eureka сервера