text-to-print: "Текст до изменений" # Property в микросервисе, которое мы будем изменять прямо на лету
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7980/realms/master
management:
  endpoints:
    web:
      exposure:
        include: refresh,busrefresh,busshutdown,health,info
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/   # URL Eureka сервера